<?php

/**
 * @license LGPLv3, http://opensource.org/licenses/LGPL-3.0
 * @copyright Aimeos (aimeos.org), 2015
 * @package Admin
 * @subpackage JQAdm
 */


namespace Aimeos\Admin\JQAdm\Product\Selection;


/**
 * Default implementation of product selection JQAdm client.
 *
 * @package Admin
 * @subpackage JQAdm
 */
class Standard
	extends \Aimeos\Admin\JQAdm\Common\Admin\Factory\Base
	implements \Aimeos\Admin\JQAdm\Common\Admin\Factory\Iface
{
	/** admin/jqadm/product/selection/standard/subparts
	 * List of JQAdm sub-clients rendered within the product selection section
	 *
	 * The output of the frontend is composed of the code generated by the JQAdm
	 * clients. Each JQAdm client can consist of serveral (or none) sub-clients
	 * that are responsible for rendering certain sub-parts of the output. The
	 * sub-clients can contain JQAdm clients themselves and therefore a
	 * hierarchical tree of JQAdm clients is composed. Each JQAdm client creates
	 * the output that is placed inside the container of its parent.
	 *
	 * At first, always the JQAdm code generated by the parent is printed, then
	 * the JQAdm code of its sub-clients. The order of the JQAdm sub-clients
	 * determines the order of the output of these sub-clients inside the parent
	 * container. If the configured list of clients is
	 *
	 *  array( "subclient1", "subclient2" )
	 *
	 * you can easily change the order of the output by reordering the subparts:
	 *
	 *  admin/jqadm/<clients>/subparts = array( "subclient1", "subclient2" )
	 *
	 * You can also remove one or more parts if they shouldn't be rendered:
	 *
	 *  admin/jqadm/<clients>/subparts = array( "subclient1" )
	 *
	 * As the clients only generates structural JQAdm, the layout defined via CSS
	 * should support adding, removing or reordering content by a fluid like
	 * design.
	 *
	 * @param array List of sub-client names
	 * @since 2016.01
	 * @category Developer
	 */
	private $subPartPath = 'admin/jqadm/product/selection/standard/subparts';
	private $subPartNames = array();


	/**
	 * Copies a resource
	 *
	 * @return string|null admin output to display or null for redirecting to the list
	 */
	public function copy()
	{
		$view = $this->getView();

		$view->selectionData = $this->getData( $view );
		$view->selectionBody = '';

		foreach( $this->getSubClients() as $client ) {
			$view->selectionBody .= $client->copy();
		}

		$tplconf = 'admin/jqadm/product/selection/template-item';
		$default = 'product/item-selection-default.php';

		return $view->render( $view->config( $tplconf, $default ) );
	}


	/**
	 * Creates a new resource
	 *
	 * @return string|null admin output to display or null for redirecting to the list
	 */
	public function create()
	{
		$view = $this->getView();

		$view->selectionData = $this->getData( $view );
		$view->selectionBody = '';

		foreach( $this->getSubClients() as $client ) {
			$view->selectionBody .= $client->create();
		}

		$tplconf = 'admin/jqadm/product/selection/template-item';
		$default = 'product/item-selection-default.php';

		return $view->render( $view->config( $tplconf, $default ) );
	}


	/**
	 * Returns a single resource
	 *
	 * @return string|null admin output to display or null for redirecting to the list
	 */
	public function get()
	{
		$view = $this->getView();

		$view->selectionData = $this->getData( $view );
		$view->selectionBody = '';

		foreach( $this->getSubClients() as $client ) {
			$view->selectionBody .= $client->get();
		}

		$tplconf = 'admin/jqadm/product/selection/template-item';
		$default = 'product/item-selection-default.php';

		return $view->render( $view->config( $tplconf, $default ) );
	}


	/**
	 * Saves the data
	 *
	 * @return string|null admin output to display or null for redirecting to the list
	 */
	public function save()
	{
		$view = $this->getView();
		$context = $this->getContext();

		$manager = \Aimeos\MShop\Factory::createManager( $context, 'product' );
		$manager->begin();

		try
		{
			$this->updateItems( $view->item, $this->getDataParams( $view ) );

			$view->selectionBody = '';

			foreach( $this->getSubClients() as $client ) {
				$view->selectionBody .= $client->save();
			}

			$manager->commit();
			return;
		}
		catch( \Aimeos\MShop\Exception $e )
		{
			$error = array( 'product-item-selection' => $context->getI18n()->dt( 'mshop', $e->getMessage() ) );
			$view->errors = $view->get( 'errors', array() ) + $error;
			$manager->rollback();
		}
		catch( \Exception $e )
		{
			$context->getLogger()->log( $e->getMessage() . ' - ' . $e->getTraceAsString() );
			$error = array( 'product-item-selection' => $e->getMessage() );
			$view->errors = $view->get( 'errors', array() ) + $error;
			$manager->rollback();
		}

		throw new \Aimeos\Admin\JQAdm\Exception();
	}


	/**
	 * Returns the sub-client given by its name.
	 *
	 * @param string $type Name of the client type
	 * @param string|null $name Name of the sub-client (Default if null)
	 * @return \Aimeos\Admin\JQAdm\Iface Sub-client object
	 */
	public function getSubClient( $type, $name = null )
	{
		/** admin/jqadm/product/selection/decorators/excludes
		 * Excludes decorators added by the "common" option from the product JQAdm client
		 *
		 * Decorators extend the functionality of a class by adding new aspects
		 * (e.g. log what is currently done), executing the methods of the underlying
		 * class only in certain conditions (e.g. only for logged in users) or
		 * modify what is returned to the caller.
		 *
		 * This option allows you to remove a decorator added via
		 * "admin/jqadm/common/decorators/default" before they are wrapped
		 * around the JQAdm client.
		 *
		 *  admin/jqadm/product/selection/decorators/excludes = array( 'decorator1' )
		 *
		 * This would remove the decorator named "decorator1" from the list of
		 * common decorators ("\Aimeos\Admin\JQAdm\Common\Decorator\*") added via
		 * "admin/jqadm/common/decorators/default" to the JQAdm client.
		 *
		 * @param array List of decorator names
		 * @since 2016.01
		 * @category Developer
		 * @see admin/jqadm/common/decorators/default
		 * @see admin/jqadm/product/selection/decorators/global
		 * @see admin/jqadm/product/selection/decorators/local
		 */

		/** admin/jqadm/product/selection/decorators/global
		 * Adds a list of globally available decorators only to the product JQAdm client
		 *
		 * Decorators extend the functionality of a class by adding new aspects
		 * (e.g. log what is currently done), executing the methods of the underlying
		 * class only in certain conditions (e.g. only for logged in users) or
		 * modify what is returned to the caller.
		 *
		 * This option allows you to wrap global decorators
		 * ("\Aimeos\Admin\JQAdm\Common\Decorator\*") around the JQAdm client.
		 *
		 *  admin/jqadm/product/selection/decorators/global = array( 'decorator1' )
		 *
		 * This would add the decorator named "decorator1" defined by
		 * "\Aimeos\Admin\JQAdm\Common\Decorator\Decorator1" only to the JQAdm client.
		 *
		 * @param array List of decorator names
		 * @since 2016.01
		 * @category Developer
		 * @see admin/jqadm/common/decorators/default
		 * @see admin/jqadm/product/selection/decorators/excludes
		 * @see admin/jqadm/product/selection/decorators/local
		 */

		/** admin/jqadm/product/selection/decorators/local
		 * Adds a list of local decorators only to the product JQAdm client
		 *
		 * Decorators extend the functionality of a class by adding new aspects
		 * (e.g. log what is currently done), executing the methods of the underlying
		 * class only in certain conditions (e.g. only for logged in users) or
		 * modify what is returned to the caller.
		 *
		 * This option allows you to wrap local decorators
		 * ("\Aimeos\Admin\JQAdm\Product\Decorator\*") around the JQAdm client.
		 *
		 *  admin/jqadm/product/selection/decorators/local = array( 'decorator2' )
		 *
		 * This would add the decorator named "decorator2" defined by
		 * "\Aimeos\Admin\JQAdm\Product\Decorator\Decorator2" only to the JQAdm client.
		 *
		 * @param array List of decorator names
		 * @since 2016.01
		 * @category Developer
		 * @see admin/jqadm/common/decorators/default
		 * @see admin/jqadm/product/selection/decorators/excludes
		 * @see admin/jqadm/product/selection/decorators/global
		 */
		return $this->createSubClient( 'product/selection/' . $type, $name );
	}


	/**
	 * Returns the products for the given codes
	 *
	 * @param array $codes List of product codes
	 * @return array List of product codes as key and items implementing \Aimeos\MShop\Product\Item\Iface as values
	 */
	protected function getProducts( array $codes )
	{
		$list = array();
		$manager = \Aimeos\MShop\Factory::createManager( $this->getContext(), 'product' );

		$search = $manager->createSearch();
		$search->setConditions( $search->compare( '==', 'product.code', $codes ) );
		$search->setSlice( 0, 0x7fffffff );

		$products = $manager->searchItems( $search, array( 'attribute' ) );

		foreach( $products as $product ) {
			$list[$product->getCode()] = $product;
		}

		return $products;
	}


	/**
	 * Returns the mapped input parameter or the existing items as expected by the template
	 *
	 * @param \Aimeos\MW\View\Iface $view View object with helpers and assigned parameters
	 * @return array Multi-dimensional associative array
	 */
	protected function getData( \Aimeos\MW\View\Iface $view )
	{
		$data = $this->getDataParams( $view );

		if( empty( $data ) ) {
			$data = $this->getDataExisting( $view );
		}

		return $data;
	}


	/**
	 * Maps the existing product variants to an associative array as expected by the template
	 *
	 * @param \Aimeos\MW\View\Iface $view View object with helpers and assigned parameters
	 * @return array Multi-dimensional associative array
	 */
	protected function getDataExisting( \Aimeos\MW\View\Iface $view )
	{
		$data = array();
		$variants = $view->item->getRefItems( 'product', null, 'default' );
		$manager = \Aimeos\MShop\Factory::createManager( $this->getContext(), 'product' );

		$search = $manager->createSearch();
		$search->setConditions( $search->compare( '==', 'product.id', array_keys( $variants ) ) );
		$search->setSortations( array( $search->sort( '+', 'product.id' ) ) );
		$search->setSlice( 0, 0x7fffffff );

		foreach( $manager->searchItems( $search, array( 'attribute' ) ) as $id => $product )
		{
			$code = $product->getCode();

			$data[$code]['product.id'] = $id;
			$data[$code]['product.label'] = $product->getLabel();

			foreach( $product->getRefItems( 'attribute', null, 'variant' ) as $attrid => $attribute )
			{
				$data[$code]['attr'][$attrid]['ref'] = $code;
				$data[$code]['attr'][$attrid]['label'] = $attribute->getLabel();
			}
		}

		return $data;
	}


	/**
	 * Maps the input parameter to an associative array as expected by the template
	 *
	 * @param \Aimeos\MW\View\Iface $view View object with helpers and assigned parameters
	 * @return array Multi-dimensional associative array
	 */
	protected function getDataParams( \Aimeos\MW\View\Iface $view )
	{
		$data = array();

		foreach( (array) $view->param( 'selection/product.code', array() ) as $pos => $code )
		{
			if( !empty( $code ) )
			{
				$data[$code]['product.id'] = $view->param( 'selection/product.id/' . $pos );
				$data[$code]['product.label'] = $view->param( 'selection/product.label/' . $pos );
			}
		}

		foreach( (array) $view->param( 'selection/attr/ref', array() ) as $pos => $code )
		{
			if( !empty( $code ) )
			{
				$id = $view->param( 'selection/attr/id/' . $pos );

				$data[$code]['attr'][$id]['ref'] = $code;
				$data[$code]['attr'][$id]['label'] = $view->param( 'selection/attr/label/' . $pos );
			}
		}

		return $data;
	}


	/**
	 * Returns the list of sub-client names configured for the client.
	 *
	 * @return array List of JQAdm client names
	 */
	protected function getSubClientNames()
	{
		return $this->getContext()->getConfig()->get( $this->subPartPath, $this->subPartNames );
	}


	/**
	 * Updates the product variants
	 *
	 * @param \Aimeos\MShop\Product\Item\Iface $product Product item with referenced domain items
	 * @param array $data Multi-dimensional associative array also used by the template
	 */
	protected function updateItems( \Aimeos\MShop\Product\Item\Iface $product, array $data )
	{
		$list = array();
		$context = $this->getContext();

		$manager = \Aimeos\MShop\Factory::createManager( $context, 'product' );
		$typeManager = \Aimeos\MShop\Factory::createManager( $context, 'product/type' );

		$typeId = $typeManager->findItem( 'default', array(), 'product' )->getId();
		$products = $this->getProducts( array_keys( $data ) );

		foreach( $data as $code => $map )
		{
			if( !isset( $products[$code] ) )
			{
				$item = $manager->createItem();
				$item->setTypeId( $typeId );
				$item->setCode( $code );
				$item->setStatus( 1 );

				if( isset( $map['product.label'] ) ) {
					$item->setLabel( $map['product.label'] );
				}

				$manager->saveItem( $item );
				$products[$code] = $item;
			}

			$list[$products[$code]->getId()] = array();
			$attr = ( isset( $map['attr'] ) ? (array) $map['attr'] : array() );

			$manager->updateListItems( $products[$code], $attr, 'attribute', 'variant' );
		}

		$manager->updateListItems( $product, $list, 'product', 'default' );
	}
}