<?php

/**
 * Error document 404
 * @author Florian Blasel
 * @copyright: Florian Blasel for Metaways Infosystems GmbH / Germany
 * @version $Id: 404.phtml 1320 2012-10-19 19:57:38Z nsendetzky $
 */

header("HTTP/1.0 404 Not Found");
global $e;
?>
<html>

<head>
	<title>404 Not Found</title>
	<style type="text/css" media="screen">
		/*<![CDATA[*/
		@import "styles/main.css";
		/*]]>*/
	</style>
</head>

<body>
	<h1>Oops...</h1>
	<hr />
	The page you are trying to access does not exist or perhaps it was removed.<br />
	Click <a href="index.php">here</a> to go to the home page.

<?php
	echo '
	<div style="overflow: visible; margin-top: 10px; padding: 2px; border: 1px dashed black;color:red;">
		<strong>Debugging information:</strong><br />
		<pre>';
		echo $e->__toString();
		echo '</pre>
	</div>';
?>

</body>
</html>