<?php

/**
 * Error document 404
 * @author Florian Blasel
 * @copyright: Florian Blasel for Metaways Infosystems GmbH / Germany
 * @version $Id: 500.phtml 1320 2012-10-19 19:57:38Z nsendetzky $
 */

header("HTTP/1.0 500 Internal Server Error");
global $e;
?>
<html>

<head>
	<title>500 Internal Server Error</title>
	<style type="text/css" media="screen">
		/*<![CDATA[*/
		@import "styles/main.css";
		/*]]>*/
	</style>
</head>

<body>
	<h1>500 Internal Server Error</h1>
	<hr />
	<strong>Application</strong> has encountered some internal error.<br />
    <br />
	Click <a href="/">here</a> to go to the home page.

<?php
	echo '
	<div style="overflow: visible; margin-top: 10px; padding: 2px; border: 1px dashed black;color:red;">
		<strong>Debugging information:</strong><br />
		<pre>';
		echo $e->__toString();
		echo '</pre>
	</div>';
?>
</body>
</html>