<?php

/**
 * @copyright Copyright (c) Metaways Infosystems GmbH, 2011
 * @license LGPLv3, http://opensource.org/licenses/LGPL-3.0
 */


/**
 * Test class for MShop_Order_Item_Base_Service_Standard.
 * Generated by Thorsten Stark on 2010-04-09.
 */
class MShop_Order_Item_Base_Service_StandardTest extends PHPUnit_Framework_TestCase
{
	private $object;
	private $values;
	private $price;
	private $attribute = array();


	protected function setUp()
	{
		$this->price = MShop_Price_Manager_Factory::createManager( TestHelper::getContext() )->createItem();

		$attrValues = array(
			'id' => 3,
			'siteid'=>99,
			'ordservid' => 42,
			'name' => 'UnitName',
			'type' => 'default',
			'code' => 'UnitCode',
			'value' => 'UnitValue',
			'mtime' => '2020-12-31 23:59:59',
			'ctime' => '2011-01-01 00:00:01',
			'editor' => 'unitTestUser'
		);

		$this->attribute = array( 'UnitCode' => new MShop_Order_Item_Base_Service_Attribute_Standard( $attrValues ) );

		$this->values = array(
			'id' => 1,
			'siteid'=>99,
			'servid' => 'ServiceID',
			'baseid' => 42,
			'code' => 'UnitCode',
			'name' => 'UnitName',
			'mediaurl' => 'Url for test',
			'type' => 'payment',
			'mtime' => -99,
			'ctime' => '2011-01-01 00:00:01',
			'editor' => 'unitTestUser'
		);

		$this->object = new MShop_Order_Item_Base_Service_Standard( $this->price, $this->values, $this->attribute );
	}

	protected function tearDown()
	{
		unset( $this->object );
	}

	public function testGetId()
	{
		$this->assertEquals( $this->values['id'], $this->object->getId() );
	}

	public function testSetId()
	{
		$this->object->setId( null );
		$this->assertEquals( null, $this->object->getId() );
		$this->assertTrue( $this->object->isModified() );

		$this->object->setId( 5 );
		$this->assertEquals( 5, $this->object->getId() );
		$this->assertFalse( $this->object->isModified() );

		$this->setExpectedException( 'MShop_Exception' );
		$this->object->setId( 6 );
	}

	public function testSetId2()
	{
		$this->setExpectedException( 'MShop_Exception' );
		$this->object->setId( 'test' );
	}

	public function testGetSiteId()
	{
		$this->assertEquals( 99, $this->object->getSiteId() );
	}

	public function testGetBaseId()
	{
		$this->assertEquals( 42, $this->object->getBaseId() );
	}

	public function testSetBaseId()
	{
		$this->object->setBaseId( 111 );
		$this->assertEquals( 111, $this->object->getBaseId() );
		$this->assertTrue( $this->object->isModified() );
	}

	public function testSetBaseIdReset()
	{
		$this->object->setBaseId( null );
		$this->assertEquals( null, $this->object->getBaseId() );
		$this->assertTrue( $this->object->isModified() );
	}

	public function testGetServiceId()
	{
		$this->assertEquals( $this->values['servid'], $this->object->getServiceId() );
	}

	public function testSetServiceId()
	{
		$this->object->setServiceId( 'testServiceID' );
		$this->assertEquals( 'testServiceID', $this->object->getServiceId() );
	}

	public function testGetCode()
	{
		$this->assertEquals( $this->values['code'], $this->object->getCode() );
	}

	public function testSetCode()
	{
		$this->object->setCode( 'testCode' );
		$this->assertEquals( 'testCode', $this->object->getCode() );
	}

	public function testGetName()
	{
		$this->assertEquals( $this->values['name'], $this->object->getName() );
	}

	public function testSetName()
	{
		$this->object->setName( 'testName' );
		$this->assertEquals( 'testName', $this->object->getName() );
		$this->assertTrue( $this->object->isModified() );
	}

	public function testGetMediaUrl()
	{
		$this->assertEquals( $this->values['mediaurl'], $this->object->getMediaUrl() );
	}

	public function testSetMediaUrl()
	{
		$this->object->setMediaUrl( 'testUrl' );
		$this->assertEquals( 'testUrl', $this->object->getMediaUrl() );
		$this->assertTrue( $this->object->isModified() );
	}

	public function testGetType()
	{
		$this->assertEquals( $this->values['type'], $this->object->getType() );
	}

	public function testSetType()
	{
		$this->object->setType( 'delivery' );
		$this->assertEquals( 'delivery', $this->object->getType() );
		$this->assertTrue( $this->object->isModified() );
	}

	public function testGetPrice()
	{
		$this->assertSame( $this->price, $this->object->getPrice() );
	}

	public function testSetPrice()
	{
		$this->price->setCosts( '5.00' );
		$this->object->setPrice( $this->price );
		$this->assertFalse( $this->object->isModified() );
		$this->assertSame( $this->price, $this->object->getPrice() );
	}

	public function testGetAttribute()
	{
		$manager = MShop_Order_Manager_Factory::createManager( TestHelper::getContext() );
		$attManager = $manager->getSubManager( 'base' )->getSubManager( 'service' )->getSubManager( 'attribute' );

		$attrItem001 = $attManager->createItem();
		$attrItem001->setCode( 'code_001' );
		$attrItem001->setValue( 'value_001' );

		$attrItem002 = $attManager->createItem();
		$attrItem002->setCode( 'code_002' );
		$attrItem002->setType( 'test_002' );
		$attrItem002->setValue( 'value_002' );

		$this->object->setAttributes( array( $attrItem001, $attrItem002 ) );

		$result = $this->object->getAttribute( 'code_001' );
		$this->assertEquals( 'value_001', $result );

		$result = $this->object->getAttribute( 'code_002', 'test_002' );
		$this->assertEquals( 'value_002', $result );

		$result = $this->object->getAttribute( 'code_002' );
		$this->assertEquals( null, $result );

		$result = $this->object->getAttribute( 'code_003' );
		$this->assertEquals( null, $result );

		$this->object->setAttributes( array() );

		$result = $this->object->getAttribute( 'code_001' );
		$this->assertEquals( null, $result );
	}

	public function testGetAttributeItem()
	{
		$manager = MShop_Order_Manager_Factory::createManager( TestHelper::getContext() );
		$attManager = $manager->getSubManager( 'base' )->getSubManager( 'service' )->getSubManager( 'attribute' );

		$attrItem001 = $attManager->createItem();
		$attrItem001->setCode( 'code_001' );
		$attrItem001->setValue( 'value_001' );

		$attrItem002 = $attManager->createItem();
		$attrItem002->setCode( 'code_002' );
		$attrItem002->setType( 'test_002' );
		$attrItem002->setValue( 'value_002' );

		$this->object->setAttributes( array( $attrItem001, $attrItem002 ) );

		$result = $this->object->getAttributeItem( 'code_001' );
		$this->assertEquals( 'value_001', $result->getValue() );

		$result = $this->object->getAttributeItem( 'code_002', 'test_002' );
		$this->assertEquals( 'value_002', $result->getValue() );

		$result = $this->object->getAttributeItem( 'code_002' );
		$this->assertEquals( null, $result );

		$result = $this->object->getAttributeItem( 'code_003' );
		$this->assertEquals( null, $result );

		$this->object->setAttributes( array() );

		$result = $this->object->getAttributeItem( 'code_001' );
		$this->assertEquals( null, $result );
	}

	public function testGetAttributes()
	{
		$this->assertEquals( $this->attribute, $this->object->getAttributes() );
	}

	public function testGetAttributesByType()
	{
		$this->assertEquals( $this->attribute, $this->object->getAttributes( 'default' ) );
	}

	public function testGetAttributesInvalidType()
	{
		$this->assertEquals( array(), $this->object->getAttributes( 'invalid' ) );
	}

	public function testSetAttributeItem()
	{
		$manager = MShop_Order_Manager_Factory::createManager( TestHelper::getContext() );
		$attManager = $manager->getSubManager( 'base' )->getSubManager( 'service' )->getSubManager( 'attribute' );

		$item = $attManager->createItem();
		$item->setCode( 'test_code' );
		$item->setType( 'test_type' );
		$item->setValue( 'test_value' );

		$this->object->setAttributeItem( $item );

		$this->assertEquals( true, $this->object->isModified() );
		$this->assertEquals( 'test_value', $this->object->getAttributeItem( 'test_code', 'test_type' )->getValue() );

		$item = $attManager->createItem();
		$item->setCode( 'test_code' );
		$item->setType( 'test_type' );
		$item->setValue( 'test_value2' );

		$this->object->setAttributeItem( $item );

		$this->assertEquals( 'test_value2', $this->object->getAttributeItem( 'test_code', 'test_type' )->getValue() );
	}

	public function testSetAttributes()
	{
		$manager = MShop_Order_Manager_Factory::createManager( TestHelper::getContext() );
		$attManager = $manager->getSubManager( 'base' )->getSubManager( 'service' )->getSubManager( 'attribute' );

		$list = array(
			$attManager->createItem(),
			$attManager->createItem(),
		);

		$this->object->setAttributes( $list );

		$this->assertEquals( true, $this->object->isModified() );
		$this->assertEquals( $list, $this->object->getAttributes() );
	}

	public function testGetTimeModified()
	{
		$this->assertEquals( $this->values['mtime'], $this->object->getTimeModified() );
	}

	public function testGetTimeCreated()
	{
		$this->assertEquals( '2011-01-01 00:00:01', $this->object->getTimeCreated() );
	}

	public function testGetEditor()
	{
		$this->assertEquals( 'unitTestUser', $this->object->getEditor() );
	}


	public function testFromArray()
	{
		$item = new MShop_Order_Item_Base_Service_Standard( new MShop_Price_Item_Standard() );

		$list = array(
			'order.base.service.id' => 1,
			'order.base.service.baseid' => 2,
			'order.base.service.serviceid' => 3,
			'order.base.service.code' => 'test',
			'order.base.service.name' => 'test item',
			'order.base.service.type' => 'delivery',
		);

		$unknown = $item->fromArray( $list );

		$this->assertEquals( array(), $unknown );

		$this->assertEquals( $list['order.base.service.id'], $item->getId() );
		$this->assertEquals( $list['order.base.service.baseid'], $item->getBaseId() );
		$this->assertEquals( $list['order.base.service.serviceid'], $item->getServiceId() );
		$this->assertEquals( $list['order.base.service.code'], $item->getCode() );
		$this->assertEquals( $list['order.base.service.name'], $item->getName() );
		$this->assertEquals( $list['order.base.service.type'], $item->getType() );
	}


	public function testToArray()
	{
		$arrayObject = $this->object->toArray();
		$this->assertEquals( count( $this->values ) + 4, count( $arrayObject ) );

		$this->assertEquals( $this->object->getId(), $arrayObject['order.base.service.id'] );
		$this->assertEquals( $this->object->getBaseId(), $arrayObject['order.base.service.baseid'] );
		$this->assertEquals( $this->object->getServiceId(), $arrayObject['order.base.service.serviceid'] );
		$this->assertEquals( $this->object->getCode(), $arrayObject['order.base.service.code'] );
		$this->assertEquals( $this->object->getName(), $arrayObject['order.base.service.name'] );
		$this->assertEquals( $this->object->getType(), $arrayObject['order.base.service.type'] );
		$this->assertEquals( $this->object->getTimeModified(), $arrayObject['order.base.service.mtime'] );
		$this->assertEquals( $this->object->getTimeCreated(), $arrayObject['order.base.service.ctime'] );
		$this->assertEquals( $this->object->getTimeModified(), $arrayObject['order.base.service.mtime'] );
		$this->assertEquals( $this->object->getEditor(), $arrayObject['order.base.service.editor'] );

		$price = $this->object->getPrice();
		$this->assertEquals( $price->getValue(), $arrayObject['order.base.service.price'] );
		$this->assertEquals( $price->getCosts(), $arrayObject['order.base.service.costs'] );
		$this->assertEquals( $price->getRebate(), $arrayObject['order.base.service.rebate'] );
		$this->assertEquals( $price->getTaxRate(), $arrayObject['order.base.service.taxrate'] );
	}

	public function testIsModified()
	{
		$this->assertFalse( $this->object->isModified() );
	}


	public function testCopyFrom()
	{
		$serviceCopy = new MShop_Order_Item_Base_Service_Standard( $this->price );

		$manager = MShop_Service_Manager_Factory::createManager( TestHelper::getContext() );

		$search = $manager->createSearch();
		$search->setConditions( $search->compare( '==', 'service.provider', 'Standard' ) );
		$services = $manager->searchItems( $search );

		if( ( $service = reset( $services ) ) === false ) {
			throw new Exception( 'No service found' );
		}

		$serviceCopy->copyFrom( $service );

		$this->assertEquals( 'unitcode', $serviceCopy->getCode() );
		$this->assertEquals( 'unitlabel', $serviceCopy->getName() );
		$this->assertEquals( 'delivery', $serviceCopy->getType() );
		$this->assertEquals( '', $serviceCopy->getMediaUrl() );

		$this->assertTrue( $serviceCopy->isModified() );
	}
}
